// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EfPowerToolsUni.Models
{
    public partial class Administrator
    {
        public int Idadministrator { get; set; }
        public string? Category { get; set; }

        public virtual User IdadministratorNavigation { get; set; } = null!;
    }
}