// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EfPowerToolsUni.Models
{
    public partial class Grade
    {
        public int Idgrade { get; set; }
        public DateOnly? Date { get; set; }
        public int Idstudent { get; set; }
        public int Idteacher { get; set; }
        public int Idcourse { get; set; }
        public short? Grade1 { get; set; }

        public virtual Course IdcourseNavigation { get; set; } = null!;
        public virtual Student IdstudentNavigation { get; set; } = null!;
        public virtual Teacher IdteacherNavigation { get; set; } = null!;
    }
}