// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using EfPowerToolsUni.Helpers;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EfPowerToolsUni.Models
{
    public partial class Student
    {
        public Student()
        {
            Grades = new HashSet<Grade>();
        }

        public int Idstudent { get; set; }
       // [JsonConverter(typeof(DateOnlyJsonConverter))]
        public DateOnly? StartDate { get; set; }
       // [JsonConverter(typeof(DateOnlyJsonConverter))]
        public DateOnly? GraduateDate { get; set; }
        [JsonIgnore]
        public virtual User IdstudentNavigation { get; set; } = null!;
        [JsonIgnore]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}