// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EfPowerToolsUni.Models
{
    public partial class Teacher
    {
        public Teacher()
        {
            Grades = new HashSet<Grade>();
        }

        public int Idteacher { get; set; }
        public short? Iddepartment { get; set; }

        public virtual Department? IddepartmentNavigation { get; set; }
        public virtual User IdteacherNavigation { get; set; } = null!;
        public virtual ICollection<Grade> Grades { get; set; }
    }
}