// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EfPowerToolsUni.Models
{
    public partial class User
    {
        public int Iduser { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
        public int? Identity { get; set; }
        public string? Firstname { get; set; }
        public string? Lastname { get; set; }

        public virtual Administrator? Administrator { get; set; }
        public virtual Student? Student { get; set; }
        public virtual Teacher? Teacher { get; set; }
    }
}