// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace EfPowerToolsUni.Models
{
    public partial class Viewgrade
    {
        public int Idgrade { get; set; }
        public DateTime? Date { get; set; }
        public short? Grade { get; set; }
        public string? Name { get; set; }
        public short? Greditpoints { get; set; }
        public string? Studentusername { get; set; }
        public string? Student { get; set; }
        public string? Username { get; set; }
        public string? Teacher { get; set; }
    }
}